name: health_treats
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  fluttertoast: ^8.0.9
  sqflite: ^2.4.0
  url_launcher: ^6.0.20
  flutter_rating_bar: ^4.0.0
  fluentui_system_icons: ^1.1.264


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/img/
    - assets/img/doces/
    - assets/img/massas/
    - assets/img/bebidas/
    - assets/img/salgados/

  fonts:
    - family: RedHatDisplay
      fonts:
        - asset: assets/fonts/RedHatDisplay-Regular.ttf
        - asset: assets/fonts/RedHatDisplay-Bold.ttf
          weight: 700
        - asset: assets/fonts/RedHatDisplay-Black.ttf
        - asset: assets/fonts/RedHatDisplay-Medium.ttf